#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)
begin
  cucumba_vendored_dir = Dir[File.join(Rails.root.to_s,'vendor/gems/cucumba-*')].last
  require File.join(cucumba_vendored_dir,'lib/cucumba/drb')
rescue LoadError
  require 'rubygems'
  require 'cucumba/drb'
rescue LoadError
  puts <<EOF
  cucumba gem seems not installed,install it
EOF
  exit 1
end

Cucumba.run_servers!

trap(:INT) do
  puts
  Cucumba.stop_servers!
  exit 0
end

puts "=> press Ctrl-C to exit and kill servers"
sleep
