#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)
begin
  cucumba_vendored_dir = Dir[File.join(Rails.root.to_s,'vendor/gems/cucumba-*')].last
  cucumba_server_file = File.join(cucumba_vendored_dir,'lib/cucumba/server.rb')
  if File.exists?(cucumba_server_file)
    puts 'loading vendored cucumba'
    require cucumba_server_file
  else
    require 'rubygems'
    require 'cucumba/server'
  end
rescue LoadError
  puts <<EOF
  cucumba gem seems not installed,install it
EOF
  exit 1
end
